language: node_js
node_js:
  - "10"
dist: trusty
sudo: false
cache: npm
branches:
  only:
    - develop
    - stating
    - master
install:
  - cd src/vue-cli3
  - npm install
script:
  - npm run build

deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    bucket: idaten.1day-release.com
    region: ap-northeast-1
    local_dir: dist
    endpoint: s3-ap-northeast-1.amazonaws.com
    skip_cleanup: true
    on:
      branch: master

notifications:
  slack:
    secure: "Rv4wNOpWOm8bU48z3JDmOOgkuKs/qJTMlLkfsX021D2lok/F105mkj9F5Ckk8QeRNgh57ufy03Kqsu1R17QiygPMTdzn0MkG6fnDCzqQGVLBwZQ79DNdMcX/Xa0/poun6408z97qew+W+HLnXO8SnTNXQ23p2HOZ+uKc8tR1rpV/f45HJ85s53/eT4e4KiRvyL6tT++7bxf33wDLCJV1CyrgnuRFO9LCac3K8ep5UmZHihkoMQrvdPbjxHD+zu+gkNWPl6ZLx2mMViASdGmtUaQ2WR+p3cDRubzDk3m5gGDcW4sjg7FlWbLAhScfkYAex/VePGVfoZa1zosynx0goFxWM+jdM7YmmGt+ADfgbKdP/e5fntf/Akm3b7ltYW7oL2basi+RgeDz3XQR5gekxFJD9jveyhkA/NzJFYJPuwPCx25fLhy0DoKmajxXmnITc3uR04ELroYQWLbkI+ZQ27/epWPrAHTcYEbed429HHH1nsn9maxk6t/QILy8+jsSk5aGhJw/zjrVhFProNtKzoFUvJOXBYC79qKchitoQRpiC9mui4GIE9nyK97xDMYywSEA2oB35tqUKu5kEAcvFiTb0TaWM5ezAI/ODeRPPHiDQIBQtA72AezBZ1towwyKb8zz5gYFUjNvVhYHLSw6MdunL9X0w2/zpxbi+Db+pYM="
