language: node_js
node_js:
  - "10"
dist: trusty
sudo: false
cache: npm
branches:
  only:
    - develop
    - stating
    - master
install:
  - cd src/vue-cli3
  - npm install
script:
  - npm run build

deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    bucket: idaten.1day-release.com
    region: ap-northeast-1
    local_dir: dist
    endpoint: s3-ap-northeast-1.amazonaws.com
    skip_cleanup: true
    on:
      branch: master

notifications:
  slack:
    secure: Cmp/N3+ajXf7kTDZS53fwENEqUx7ZvQU1WU+P8OteYHGoKfbch4wid2WRczXFCXhzBREAzcLimpDGE/1j30yiwlMyYTUMuoG51362lIUghUM/iSm2/B8j4lP2X7XskMGvfwSkXIVscX6aY3b/OGR6c4moU8wyQLOOn9G/uHHMbqJTi9w86yGC8V4YhNv7rvuo5hAiW83U+c36cCzFnsO372x5F0nPOR6et1u7GbEqIHnAnEz7zlxEYYK4Y4qZ2qf7cKCCvVo0FwvrrxzDn4v2lL8KdM6+fuZATM+RH4RNgq6Ttio0VOMAQmtmRX/ljf4flbnjvX5O0RpM0Nr4CN0GLIHFqaeHyVieGE/MvxkBpTDZPDlrKGdQZAnu3TiYr8kg06hljp471ydla74OyBhKCRP06dRuULtveNoWqsGZ/R/TNvfr3Kd/woEt7X5XtmB7pKPQAGhrDKFzoxuslOvs/74p7NhX64FzPZmDZIUNmXAaIrq0U++vaBriFjSDzHpvkKenfOt4N+FXsQmY7XbNdgnxL+YSQ92ndn3qP1YPOijaohSvQ+hnDvThpvlqCqPle+LJIRF60JkRZNKOfVhxRPy9yHNlpImZCTrqrkISG6WB+RqYjUKt2uKj+aSpfHD/La9k9cEDUYaL8bGoAXjYec9QMqeCb3bka3RohxO8ss=
