language: node_js
node_js:
  - "10"
dist: trusty
sudo: false
cache: npm
branches:
  only:
    - develop
    - stating
    - master
install:
  - cd src/vue-cli3
  - npm install
script:
  - npm run build
deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    bucket: idaten.1day-release.com
    region: ap-northeast-1
    local_dir: dist
    endpoint: s3-ap-northeast-1.amazonaws.com
    skip_cleanup: true
    on:
      branch: master
notifications:
  dd:
    secure: bUv1IUCXYSCMjZ/CN/T2jFuz7Gq/+lDh6J8BAtwWLy0jbP2/g1eQ2J7UypH8xYYqcDyuX+dedbywnn/RKHfS5LpA5tlYzu2UyaNg/NvVMUkSgp38vCCV6PMh8OttMNAABjsDtP/AYekva9emenGOyzSXYo/vNHMl5LuRbn1tOE928ImWQXF2vBUJmOgDNMdY1bqcbiIB5/dpLFBCzNchH0HDRTQQespA9cHTB2bPGt3Z/RsQuDvYwDa4AFWuRlCNG14FTNRu235b06izbMAynsx5ECMHGGTF3HxvXx4vmGRdsoj3H36/Budc128a08Fx8tJUTnoSCyfh52weCl1PbdBqA/ddTkAUE3XSiiMmhAV3zxsWJQAoTnlmEJ/2tpnj0CwYwRXQBpYd3TJhQ3qgbH6K6+x4mx4W0nnM8tfR4D1cr3OvHLOPNBcnevfiwUOSQe2YV+zP9HZ+Naz27Xiis6iVU98CLIwRAOE2WYk9ucG93EhxbKg7xDZA7vaf0pFVumrt6rl1f0lfb0wZBh78bX+cbWKoJ23XpbTGnfd5hVy1Yuf5NykqWfU1LsYUSKKv0ZccdHDbbBOgx3zlwXb13Eka0LbqEq2r3Q4aapBTfesbtvAqUqzu0xsoo9oFMcJGPiwfR05LZ/TB0KHV4791+IZSiyY72P8a+xzkS1BvcGM=
