language: node_js
node_js:
- '10'
dist: trusty
sudo: false
cache: npm
branches:
  only:
  - develop
  - stating
  - master
install:
- npm install newman
- cd app
- npm install
- cd ../
script:
- node_modules/.bin/newman run ./server/tests/postman/idaten-api.postman_collection.json -e ./server/tests/postman/idaten-api.postman_environment.json
- cd app
- npm run test:unit
- npm run build
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: idaten.1day-release.com
  region: ap-northeast-1
  local_dir: dist
  endpoint: s3-ap-northeast-1.amazonaws.com
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack:
    secure: JGTgyjWYGy5lwRvbwTBxPwkLZBrU5y3iwFnd+3O+1RhZhxXgFqVDE/+P4C/mlI4iYX9EAOEGyFh086RucWbT+T9h2z/QlCBwq3Ulg/o2GapCxz6VX38BOb4/E1YPDPKUisFZB/fnUhn04m7VkHtoIgED/jojclcoyHH3LJDapjTG13BKnhsnSwwdizhRIaUscqrjZl5u73vzZvuDUxs0c/wjm8BG+UmAXNjvZAETDoA1JT7/Qrf7uzjEk+heWjKSe2e+rV384DE4uE8yfLyDBZ48rIoqpXDqI5yPo/VLvQOh+4ADzp1YHXRIJETwiLfZGamoyXWnsb0ghdN1ChvLvZkkCSxUTuoad3AbMHNxfJrCXi85ik6bxIWHdgyvJbGgnELCy6qHtbbjz05ZpcL6ghexgseNEaFcUY60htQvFtkFj3kvT2aNovK88r6K/GY3t9xJ05eFL8XcmJlVnvYrjk8KRAjTG6R66A6BD+w9CeSqQvJ4Bl0wq0Th/VNE8tyBme/GiKpHus/sY6E1ddAw+JMhHLOgvA/0urpfqAZF07ZXiJC2jjHgQl1ZUNQmYvPqgLJiKm9QCIiA8oB4DFHdNZcxFKuQFTx9f7F8yq8SqiQlamuFk8n+0iiKc6BXgUHbVbwM5ZC9zn3FoxgxKIhwTNGQa/wUOvS1QZWLfNmAvME=
