service: idaten # NOTE: update this with your service name

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.idaten.1day-release.com
    basePath: "api"
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: go1.x

  stage: api
  region: ap-northeast-1

  iamRoleStatements:
    - Effect: "Allow"
      Resource: "arn:aws:dynamodb:ap-northeast-1:*:*"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  login:
    handler: bin/hello
    events:
      - http:
          path: auth/login
          method: get
  logout:
    handler: bin/world
    events:
      - http:
          path: auth/logout
          method: get
  slideslist:
    handler: bin/slides-list
    events:
      - http:
          path: slides
          method: get
